### ISSUE TITLE
bug in guess_ifiction function in babel_multi_functions.c

### ISSUE THREAD

**Issue by Kirtai** [iftechfoundation/babel-tool#13]
In this function, buff is filled by fread and i is treated as the number of bytes read,
```
 i=fread(buf,1023,1,f);
```
so that
```
buf[i]=0;
```
adds a null to the end. However, fread's return value is *the number of items read*, not the number of bytes read. Since fread is told to read one item of 1023 bytes, this means that i=1 and the null is placed in the second byte of buff, instead of at the end. This causes the test to fail for all ifiction files.

Temporarily replacing 
```
buff[i]=0
```
with 
```
 buf[1023]=0;
```
lets it work for now.

This is on Kubuntu 20.10

I ran into this when using babel-marry.pl

**Comment by erkyrath** [comment]
Thanks. It seems clear that the arguments are just in the wrong order; it's supposed to read up to 1023 bytes and look at the number of bytes read.

Fixed.

**Comment by erkyrath** [comment]
The bug was preventing `babel -complete` from working correctly -- it would erroneously say "File ... does not appear to be an iFiction file".
