### ISSUE TITLE
Get which game created a glksave

### ISSUE THREAD

**Issue by cibersheep** [iftechfoundation/babel-tool#14]
Maybe it's out of scope here but:
I know the glksave has the route and game that created it. Would it be possible to get that info from babel?
Or, is there a tool that already does that?

**Comment by angstsmurf** [comment]
While Bocfel seems to store the path to the game file in its saves (in an `IntD` chunk), the other interpreters I've looked at (Lectrote, Zoom, Frotz) do not.

Still, a tool to show the information from a Quetzal file (or indeed other save formats) would be interesting and useful, but I don't think anyone has written one yet. [`ckifzs`](https://github.com/borg323/jzip/blob/master/ckifzs.c), which is included in [the `jzip` source](https://github.com/borg323/jzip), only seems to check that all the necessary chunks are in place.

**Comment by cibersheep** [comment]
Oh, I see... I've been using mainly bocfel and level9 interpreter saved files which include the game it was saved from and assumed (incorrectly) that all did. Now I've checked other interpreters (agility, tads, magnetic scrolls) and you are right, they don't include it.
Interesting

**Comment by erkyrath** [comment]
Z-machine/Glulx interpreters store information that can verify the game file (its header and checksum, basically) but not its path. Files wander around.

**Comment by cibersheep** [comment]
That sounds a better approach. So, is a way of getting the checksum in the save file? Or is it out of the scope of babel-tool?

Now, I create a database when saving, to keep track of it

**Comment by angstsmurf** [comment]
You can read about the checksums in the Quetzal save file format standard here: 
https://www.inform-fiction.org/zmachine/standards/quetzal/index.html#five

Most Z-machine and Glulx interpreters support this standard, and contain code to read the checksum contained in the save file and compare it to the currently running game file. See for example Glulxe [here](https://github.com/erkyrath/glulxe/blob/master/serial.c#L486-L507) and Bocfel [here](https://github.com/garglk/garglk/blob/master/terps/bocfel/stack.c#L924-L937).

To guess the game from just the save file, you would need a database of games and their checksums. Babel does not contain such a database. It would make more sense for IFDB to add this, but currently it does not store checksums.

It is possible to re-create the IFIDs for older Z-code games using the IFhd info in the save file and match this against IFDB, but it will only work for some games.

**Comment by erkyrath** [comment]
> To guess the game from just the save file, you would need a database of games and their checksums. Babel does not contain such a database. It would make more sense for IFDB to add this, but currently it does not store checksums.

The most immediately practical idea here is for your interpreter to keep a *local* database of every game file that you play. Then, when it sees a save file, it probably knows where the associated game file is. Or at least where the game file was last time you played it!

I think Zoom did something like this, although it's been a while.

**Comment by cibersheep** [comment]
Thanks for the answers.
I guess then I'm in the correct path. I did a sqlite db that stores info of the games being imported. When player saves, I store the info for comparison.

Quite ugly code but: https://gitlab.com/cibersheep/gelek-vanilla/-/blob/master/qml/db/db.js

So, I close this issue ;)

**Comment by cibersheep** [comment]
Ouh... I just realized that is my code addind the info for some saved games ¬¬
Can you believe that?
