### ISSUE TITLE
Scapesghost (DOS) -format "executable" instead of "level9"

### ISSUE THREAD

**Issue by cibersheep** [iftechfoundation/babel-tool#15]
Doing `babel -format GAMEDAT1.DAT` on Scapeghost for PC returns:
`Format: executable (non-authoritative)`

I have two copies of the game (only GAMEDAT1.DAT are different) md5sum:
```
a8375aa2ca595694c315cb95e92b0ced  GAMEDAT1.DAT - Identified by terp as (PC/ST)
139d1f07b33b3178ab9a93d5dc61cfac  GAMEDAT1.DAT - Identified by terp as (amiga)
6d86951023236d8a417663fb8dd1d94c  GAMEDAT2.DAT
f109218800ce4d9cd03c6b3d90e30010  GAMEDAT3.DAT
```

How can I get the hex code to detect them?

**Comment by cibersheep** [comment]
Oh, if I tar the picture files and one of the `GAMEDAT*.DAT`, babel detects it correctly.
If I tar them all together (all pictures and DAT), only detects it as the third part of the game

**Comment by erkyrath** [comment]
I'm afraid I don't know anything about Level 9 game format, and I don't have the game files to check.

You may want to bring this up on the forum and talk to people who know more. If there's a way to improve the Babel code, I'll be happy to accept it.

**Comment by cibersheep** [comment]
That's fair. 
I'll post in the forum about it.

**Comment by angstsmurf** [comment]
As far as I can tell, #18 fixed this, so I  guess this can be closed.

**Comment by cibersheep** [comment]
Oh. Sorry about that... clos--
