### ISSUE TITLE
Alan IFIDs come out in lower case

### ISSUE THREAD

**Issue by erkyrath** [iftechfoundation/babel-tool#23]
```
% ./babel -ifid test/alan/valid.a3c
IFID: c065a752-a476-a252-731f-e9fe96fcdc6d
```

The IFID should be upper-case to be consistent with other cases.

**Comment by angstsmurf** [comment]
Right, and the Hugo detection should turn the lowercase one into uppercase, I suppose.

**Comment by angstsmurf** [comment]
#21 now outputs all IFIDs in uppercase.
