### ISSUE TITLE
Crosscompiling Babel alway x86-64 binary

### ISSUE THREAD

**Issue by cibersheep** [iftechfoundation/babel-tool#28]
I'm crosscompiling babel (in addition to other tools) targeting amd64, arm64 and armhf architectures.
While the rest of the tools (remglk, various interpreters, blorblib) compiles with no issues, Babel ends up compiling into a x86-64 binary (the arch of my host machine).

Is babel forced to build for x86? Am I doing something wrong?
Now the workaround I found is add by hand the specific gcc compiler to the target arch. Is there a better workaround?

**Comment by erkyrath** [comment]
I didn't write the Makefile but I don't see it doing anything unusual with architectures.

Are you doing this on Linux?

**Comment by cibersheep** [comment]
> I didn't write the Makefile but I don't see it doing anything unusual with architectures.

I was also searching for any parameter, and I seem not to find any.

> Are you doing this on Linux?

Yep, I'm on Ubuntu 20.04. It's a bit hard to explain though, as I'm building targetting Ubuntu Touch. The tool to crosscompile ([clickable](https://clickable-ut.dev/)) uses a docker image. That would be my next guess, that the docker image has a configuration bug.

But I'm compiling in the same way [blorblib](https://github.com/erkyrath/blorblib/tree/d87872dd7e8cdfab3e82bddb62a90057a105fe71) with success

**Comment by cibersheep** [comment]
I also have open an issue on the tool:
Just for reference: https://gitlab.com/clickable/clickable/-/issues/341

**Comment by cibersheep** [comment]
Found it :)
Thanks
