### ISSUE TITLE
Adrift 5 not handled

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/babel-tool#30]
Adrift 5 story files contain an embedded iFiction record, which includes their IFID (and other details).

**Comment by erkyrath** [comment]
Commit https://github.com/iftechfoundation/babel-tool/commit/7adac3e560cfc830e27e8e243c399106d3665486 should handle this.

**Comment by curiousdannii** [comment]
Thanks! It is now finding the IFID, but not the other metadata.

Aside, there's now two files with `find_text_in_file`, should it be made a shared function?

**Comment by erkyrath** [comment]
Sigh, right, that's get_story_file_metadata_extent() and get_story_file_metadata(), isn't it?

As for find_text_in_file(), I'm gonna wait until there's a third example. They might not all have the same requirements.

**Comment by curiousdannii** [comment]
Think so, but not completely sure.

**Comment by erkyrath** [comment]
Added commit https://github.com/iftechfoundation/babel-tool/commit/a18e302366406cb69cd8b436c69799fd228f9dd2 . It seems to work.

I'll see about generating a minimal ADRIFT 5 file for the test directory.

**Comment by erkyrath** [comment]
I built test4.taf and test5.taf and added them to the test directory.

**Comment by curiousdannii** [comment]
Thank you!
