### ISSUE TITLE
Move warnings to end of -format output

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/babel-tool#33]
The -format command sometimes outputs a warning, such as if the file doesn't have an extension. This broke Parchment's sitegen service as I wasn't accounting for that possibility.

What if the warning was moved to the end, so that the first three lines of the command are always the same? That would make tools which automatically parse it more reliable.

**Comment by erkyrath** [comment]
This is the warning at babel.c:231?

**Comment by curiousdannii** [comment]
Yep that's right. It might be the only warning, I didn't check for others.

**Comment by erkyrath** [comment]
There's a bunch in the ifiction_parse() function. I don't remember what commands call that.

Maybe a "-no-warnings" option would make more sense?

**Comment by curiousdannii** [comment]
Yeah that could work too.

**Comment by erkyrath** [comment]
Done: https://github.com/iftechfoundation/babel-tool/pull/36
