### ISSUE TITLE
spy1.blb will crash babel-tool

### ISSUE THREAD

**Issue by angstsmurf** [iftechfoundation/babel-tool#7]
The strange blorb file downloadable from here will crash Babel:
https://inform-fiction.org/zmachine/standards/blorb/index.html#nine

EXC_BAD_ACCESS  at this line, with j set to 944924012 (on my machine):
https://github.com/iftechfoundation/babel-tool/blob/master/blorb.c#L123

**Comment by erkyrath** [comment]
That's certainly a bad blorb file. I can't read it with https://github.com/erkyrath/glk-dev/blob/master/blorbtool.py either.

I've added a length check to blorb.c to avoid crashing.

```
% ./babel -story ~/Downloads/spy1.blb
Error: Did not recognize format of story file
% ./babel -ifid ~/Downloads/spy1.blb
IFID: B4F71F99FC2BE72AD9C459A4219BF3CD
```
