### ISSUE TITLE
Babel detects font .hex files as a Hugo game

### ISSUE THREAD

**Issue by angstsmurf** [iftechfoundation/babel-tool#8]
At least the font files in this folder:
https://github.com/garglk/garglk/tree/master/garglk

They are all detected as a Hugo game with IFID `HUGO-117-6E-73-igned-ch`

I also tried other random files with a .hex suffix, but those were rejected.

**Comment by erkyrath** [comment]
Apparently Hugo files don't have a magic number prefix. The code in https://github.com/iftechfoundation/babel-tool/blob/master/hugo.c just checks that the serial number looks plausible (ASCII) and the following values don't look like invalid addresses. A plaintext file (which those .hex files are) may pass this test.

I don't know of a better algorithm.

**Comment by angstsmurf** [comment]
[The Hugo interpreter ](https://github.com/garglk/garglk/blob/master/terps/hugo/source/hemisc.c#L1310-L1362) seems to read the first char from the game file into a `game_version` variable, compare it to a `check_version` number (33), and bail if it is larger than this. If the flag COMPILE_V25 is set, it does a different check that fails if `game_version` is greater than 39.

That doesn't seem like it would be too hard to replicate in the Babel code.

**Comment by erkyrath** [comment]
I've put in this check (first byte no greater than 39). Obviously this is still a heuristic; an ASCII file that starts with a number will still pass the check.
