### ISSUE TITLE
babel-infocom.pl fails on a case sensitive filesystem

### ISSUE THREAD

**Issue by Kirtai** [iftechfoundation/babel-tool#9]
When running babel-infocom.pl with the blorbs from [here](http://babel.ifarchive.org/infocom.html), the script fails to work on a case sensitive file system since it is looking for the file babel-iFiction (note the capital F) but the supplied file is named babel.ifiction (lower case F).

**Comment by erkyrath** [comment]
Would it make sense for the babel-infocom.pl script to check for both `babel.iFiction` and `babel.ifiction`?

**Comment by Kirtai** [comment]
That would work, but a case insensitive compare would be better.

**Comment by erkyrath** [comment]
I don't believe there's a way to do this (Perl's `-e` operator) in a case-insensitive way on a case-sensitive filesystem. I would need to glob or walk the directory, and that's too much of a headache for this case.

The line in question looks like:

    if (-e "$fromdir"."babel.iFiction")

**Comment by erkyrath** [comment]
See updated script: 

https://github.com/iftechfoundation/babel-tool/blob/master/extras/babel-infocom.pl

**Comment by Kirtai** [comment]
Thank you
